2025-04-08 16:10:29   main.py --matcher sift-lg --max_num_keypoints 2048 --img_size 512 --data_dir data --log_dir out_sift-lg --save_images --device cuda
2025-04-08 16:10:29   Arguments: Namespace(matcher='sift-lg', max_num_keypoints=2048, num_iterations=4, img_size=512, save_images=True, device='cuda', data_dir='data', log_dir='out_sift-lg')
2025-04-08 16:10:29   The outputs are being saved in logs/out_sift-lg/2025-04-08_16-10-29
2025-04-08 16:10:31   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=0 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:32   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=1 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:33   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=2 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:33   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=3 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:34   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=4 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:35   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=5 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:36   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=6 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:36   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=7 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:37   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=8 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:38   @-35.4@-72.5@-34.0@-71.0@29@1150@75@ISS050-E-35441@ pred_idx=9 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:38   @36.4@38.2@35.4@39.3@0@1150@10@ISS050-E-70536@ pred_idx=0 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:39   @36.4@38.2@35.4@39.3@0@1150@10@ISS050-E-70536@ pred_idx=1 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:40   @36.4@38.2@35.4@39.3@0@1150@10@ISS050-E-70536@ pred_idx=2 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:41   @36.4@38.2@35.4@39.3@0@1150@10@ISS050-E-70536@ pred_idx=3 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:41   @36.4@38.2@35.4@39.3@0@1150@10@ISS050-E-70536@ pred_idx=4 iteration=00 MSG4_ERROR Error too many values to unpack (expected 4)
2025-04-08 16:10:41   
Traceback (most recent call last):
  File "/gpfs/home3/scur2410/EarthMatch_Master_Duster/main.py", line 73, in <module>
    query_image = matcher.image_loader(query_path, args.img_size).to(args.device)
  File "/gpfs/home3/scur2410/EarthMatch_Master_Duster/image-matching-models/matching/im_models/base_matcher.py", line 46, in image_loader
    return BaseMatcher.load_image(path, resize, rot_angle)
  File "/gpfs/home3/scur2410/EarthMatch_Master_Duster/image-matching-models/matching/im_models/base_matcher.py", line 52, in load_image
    img = tfm.ToTensor()(Image.open(path).convert("RGB"))
  File "/home/scur2410/.local/lib/python3.10/site-packages/PIL/Image.py", line 984, in convert
    self.load()
  File "/home/scur2410/.local/lib/python3.10/site-packages/PIL/ImageFile.py", line 300, in load
    n, err_code = decoder.decode(b)
KeyboardInterrupt

